const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
const GET_PROJECTS_ERROR = 'GET_PROJECTS_ERROR'
const GET_PROJECTS_START = 'GET_PROJECTS_START'
const SET_CURRENT_PROJECT_SUCCESS = 'SET_CURRENT_PROJECT_SUCCESS'
const SET_CURRENT_PROJECT_ERROR = 'SET_CURRENT_PROJECT_ERROR'
const SET_CURRENT_PROJECT_START = 'SET_CURRENT_PROJECTS_START'

const UPDATE_PROJECTS_SUCCESS = 'UPDATE_PROJECTS_SUCCESS'
const UPDATE_PROJECTS_ERROR = 'UPDATE_PROJECTS_ERROR'
const UPDATE_PROJECTS_START = 'UPDATE_PROJECTS_START'

export const projectsActions = {
    GET_PROJECTS_ERROR,
    GET_PROJECTS_START,
    GET_PROJECTS_SUCCESS,
    UPDATE_PROJECTS_ERROR,
    UPDATE_PROJECTS_START,
    UPDATE_PROJECTS_SUCCESS,
    SET_CURRENT_PROJECT_START,
    SET_CURRENT_PROJECT_SUCCESS,
    SET_CURRENT_PROJECT_ERROR
}