const GET_TEAMS_START = 'GET_TEAMS_START'
const GET_TEAMS_SUCCESS = 'GET_TEAMS_SUCCESS'
const GET_TEAMS_ERROR = 'GET_TEAMS_ERROR'

const UPDATE_TEAMS_START = 'UPDATE_TEAMS_START'
const UPDATE_TEAMS_SUCCESS = 'UPDATE_TEAMS_SUCCESS'
const UPDATE_TEAMS_ERROR = 'UPDATE_TEAMS_ERROR'

const ADD_MEMBER_START = 'ADD_MEMBER_START'
const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS'
const ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR'

const GET_MEMBER_START = 'GET_MEMBER_START'
const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS'
const GET_MEMBER_ERROR = 'GET_MEMBER_ERROR'


const UPDATE_MEMBER_START = 'UPDATE_MEMBER_START'
const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS'
const UPDATE_MEMBER_ERROR = 'UPDATE_MEMBER_ERROR'

const DELETE_MEMBER_START = 'DELETE_MEMBER_START'
const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS'
const DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR'


export const teamsActions = {
    GET_TEAMS_START,
    GET_TEAMS_SUCCESS,
    GET_TEAMS_ERROR,

    UPDATE_TEAMS_START,
    UPDATE_TEAMS_SUCCESS,
    UPDATE_TEAMS_ERROR,

    GET_MEMBER_START,
    GET_MEMBER_SUCCESS,
    GET_MEMBER_ERROR,

    UPDATE_MEMBER_START,
    UPDATE_MEMBER_SUCCESS,
    UPDATE_MEMBER_ERROR,

    DELETE_MEMBER_START,
    DELETE_MEMBER_SUCCESS,
    DELETE_MEMBER_ERROR,

    ADD_MEMBER_START,
    ADD_MEMBER_SUCCESS,
    ADD_MEMBER_ERROR,
}