const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
const CREATE_MEETING_ERROR = 'CREATE_MEETING_ERROR'
const CREATE_MEETING_START = 'CREATE_MEETING_START'
const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS'
const UPDATE_MEETING_ERROR = 'UPDATE_MEETING_ERROR'
const UPDATE_MEETING_START = 'UPDATE_MEETING_START'

export const OrgActionsTypes = {
    CREATE_MEETING_ERROR,
    CREATE_MEETING_START,
    CREATE_MEETING_SUCCESS,
    UPDATE_MEETING_ERROR,
    UPDATE_MEETING_START,
    UPDATE_MEETING_SUCCESS
}