const CREATE_MEETING_START = 'CREATE_MEETING_START'
const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
const CREATE_MEETING_ERROR = 'CREATE_MEETING_ERROR'
const GET_MEETINGS_START = 'GET_MEETINGS_START'
const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS'
const GET_MEETINGS_ERROR = 'GET_MEETINGS_ERROR'

const GET_ONE_MEETING_START = 'GET_ONE_MEETING_START'
const GET_ONE_MEETING_SUCCESS = 'GET_ONE_MEETING_SUCCESS'
const GET_ONE_MEETING_ERROR = 'GET_ONE_MEETING_ERROR'
const UPDATE_MEETING_START = 'UPDATE_MEETING_START'
const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS'
const UPDATE_MEETING_ERROR = 'UPDATE_MEETING_ERROR'

const CREATE_MEETING_AGENDA_START = 'CREATE_MEETING_AGENDA_START'
const CREATE_MEETING_AGENDA_SUCCESS = 'CREATE_MEETING_AGENDA_SUCCESS'
const CREATE_MEETING_AGENDA_ERROR = 'CREATE_MEETING_AGENDA_ERROR'
const GET_MEETING_AGENDA_START = 'GET_MEETING_AGENDA_START'
const GET_MEETING_AGENDA_SUCCESS = 'GET_MEETING_AGENDA_SUCCESS'
const GET_MEETING_AGENDA_ERROR = 'GET_MEETING_AGENDA_ERROR'
const UPDATE_MEETING_AGENDA_START = 'UPDATE_MEETING_AGENDA_START'
const UPDATE_MEETING_AGENDA_SUCCESS = 'UPDATE_MEETING_AGENDA_SUCCESS'
const UPDATE_MEETING_AGENDA_ERROR = 'UPDATE_MEETING_AGENDA_ERROR'
const DELETE_MEETING_AGENDA_START = 'DELETE_MEETING_AGENDA_START'
const DELETE_MEETING_AGENDA_SUCCESS = 'DELETE_MEETING_AGENDA_SUCCESS'
const DELETE_MEETING_AGENDA_ERROR = 'DELETE_MEETING_AGENDA_ERROR'

const CREATE_MEETING_NOTES_START = 'CREATE_MEETING_NOTES_START'
const CREATE_MEETING_NOTES_SUCCESS = 'CREATE_MEETING_NOTES_SUCCESS'
const CREATE_MEETING_NOTES_ERROR = 'CREATE_MEETING_NOTES_ERROR'
const GET_MEETING_NOTES_START = 'GET_MEETING_NOTES_START'
const GET_MEETING_NOTES_SUCCESS = 'GET_MEETING_NOTES_SUCCESS'
const GET_MEETING_NOTES_ERROR = 'GET_MEETING_NOTES_ERROR'
const UPDATE_MEETING_NOTE_START = 'UPDATE_MEETING_NOTES_START'
const UPDATE_MEETING_NOTE_SUCCESS = 'UPDATE_MEETING_NOTES_SUCCESS'
const UPDATE_MEETING_NOTE_ERROR = 'UPDATE_MEETING_NOTES_ERROR'
const DELETE_MEETING_NOTE_START = 'DELETE_MEETING_NOTES_START'
const DELETE_MEETING_NOTE_SUCCESS = 'DELETE_MEETING_NOTES_SUCCESS'
const DELETE_MEETING_NOTE_ERROR = 'DELETE_MEETING_NOTES_ERROR'

const CREATE_MEETING_INVITEE_START = 'CREATE_MEETING_INVITEE_START'
const CREATE_MEETING_INVITEE_SUCCESS = 'CREATE_MEETING_INVITEE_SUCCESS'
const CREATE_MEETING_INVITEE_ERROR = 'CREATE_MEETING_INVITEE_ERROR'
const GET_MEETING_INVITEES_START = 'GET_MEETING_INVITEES_START'
const GET_MEETING_INVITEES_SUCCESS = 'GET_MEETING_INVITEES_SUCCESS'
const GET_MEETING_INVITEES_ERROR = 'GET_MEETING_INVITEES_ERROR'
const UPDATE_MEETING_INVITEE_START = 'UPDATE_MEETING_INVITEE_START'
const UPDATE_MEETING_INVITEE_SUCCESS = 'UPDATE_MEETING_INVITEE_SUCCESS'
const UPDATE_MEETING_INVITEE_ERROR = 'UPDATE_MEETING_INVITEE_ERROR'
const DELETE_MEETING_INVITEE_START = 'DELETE_MEETING_INVITEE_START'
const DELETE_MEETING_INVITEE_SUCCESS = 'DELETE_MEETING_INVITEE_SUCCESS'
const DELETE_MEETING_INVITEE_ERROR = 'DELETE_MEETING_INVITEE_ERROR'


export const meetingsActions = {
    CREATE_MEETING_START,
    CREATE_MEETING_SUCCESS,
    CREATE_MEETING_ERROR,
    GET_MEETINGS_START,
    GET_MEETINGS_SUCCESS,
    GET_MEETINGS_ERROR,
    GET_ONE_MEETING_START,
    GET_ONE_MEETING_SUCCESS,
    GET_ONE_MEETING_ERROR,
    UPDATE_MEETING_START,
    UPDATE_MEETING_SUCCESS,
    UPDATE_MEETING_ERROR,

    CREATE_MEETING_AGENDA_START,
    CREATE_MEETING_AGENDA_SUCCESS,
    CREATE_MEETING_AGENDA_ERROR,
    GET_MEETING_AGENDA_START,
    GET_MEETING_AGENDA_SUCCESS,
    GET_MEETING_AGENDA_ERROR,
    UPDATE_MEETING_AGENDA_START,
    UPDATE_MEETING_AGENDA_SUCCESS,
    UPDATE_MEETING_AGENDA_ERROR,
    DELETE_MEETING_AGENDA_START,
    DELETE_MEETING_AGENDA_SUCCESS,
    DELETE_MEETING_AGENDA_ERROR,

    CREATE_MEETING_NOTES_START,
    CREATE_MEETING_NOTES_SUCCESS,
    CREATE_MEETING_NOTES_ERROR,
    GET_MEETING_NOTES_START,
    GET_MEETING_NOTES_SUCCESS,
    GET_MEETING_NOTES_ERROR,
    UPDATE_MEETING_NOTE_START,
    UPDATE_MEETING_NOTE_SUCCESS,
    UPDATE_MEETING_NOTE_ERROR,
    DELETE_MEETING_NOTE_START,
    DELETE_MEETING_NOTE_SUCCESS,
    DELETE_MEETING_NOTE_ERROR,

    CREATE_MEETING_INVITEE_START,
    CREATE_MEETING_INVITEE_SUCCESS,
    CREATE_MEETING_INVITEE_ERROR,
    GET_MEETING_INVITEES_START,
    GET_MEETING_INVITEES_SUCCESS,
    GET_MEETING_INVITEES_ERROR,
    UPDATE_MEETING_INVITEE_START,
    UPDATE_MEETING_INVITEE_SUCCESS,
    UPDATE_MEETING_INVITEE_ERROR,
    DELETE_MEETING_INVITEE_START,
    DELETE_MEETING_INVITEE_SUCCESS,
    DELETE_MEETING_INVITEE_ERROR
}