const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS'
const CREATE_MEETING_ERROR = 'CREATE_MEETING_ERROR'
const CREATE_MEETING_START = 'CREATE_MEETING_START'
const UPDATE_MEETING_SUCCESS = 'UPDATE_MEETING_SUCCESS'
const UPDATE_MEETING_ERROR = 'UPDATE_MEETING_ERROR'
const UPDATE_MEETING_START = 'UPDATE_MEETING_START'
const GET_MEETINGS_START = 'GET_MEETINGS_START'
const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS'
const GET_MEETINGS_ERROR = 'GET_MEETINGS_ERROR'
const GET_ONE_MEETING_START = 'GET_ONE_MEETING_START'
const GET_ONE_MEETING_SUCCESS = 'GET_ONE_MEETING_SUCCESS'
const GET_ONE_MEETING_ERROR = 'GET_ONE_MEETING_ERROR'

export const meetingsActions = {
    CREATE_MEETING_START,
    CREATE_MEETING_SUCCESS,
    CREATE_MEETING_ERROR,
    UPDATE_MEETING_START,
    UPDATE_MEETING_SUCCESS,
    UPDATE_MEETING_ERROR,
    GET_MEETINGS_START,
    GET_MEETINGS_SUCCESS,
    GET_MEETINGS_ERROR,
    GET_ONE_MEETING_START,
    GET_ONE_MEETING_SUCCESS,
    GET_ONE_MEETING_ERROR
}