const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR'
const GET_PROFILE_START = 'GET_PROFILE_START'
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR'
const UPDATE_PROFILE_START = 'UPDATE_PROFILE_START'

export const profileActions = {
    GET_PROFILE_ERROR,
    GET_PROFILE_START,
    GET_PROFILE_SUCCESS,
    UPDATE_PROFILE_ERROR,
    UPDATE_PROFILE_START,
    UPDATE_PROFILE_SUCCESS
}