const SET_CURRENT_ORG_SUCCESS = 'CREATE_CURRENT_ORG'
const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS'
const CREATE_ORG_ERROR = 'CREATE_ORG_ERROR'
const CREATE_ORG_START = 'CREATE_ORG_START'
const UPDATE_ORG_SUCCESS = 'UPDATE_ORG_SUCCESS'
const UPDATE_ORG_ERROR = 'UPDATE_ORG_ERROR'
const UPDATE_ORG_START = 'UPDATE_ORG_START'
const GET_ORG_START = 'GET_ORG_START'
const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS'
const GET_ORG_ERROR = 'GET_ORG_ERROR'
const DELETE_INVITE_SUCCESS = 'DELETE_INVITE_SUCCESS'
const DELETE_INVITE_ERROR = 'DELETE_INVITE_ERROR'
const UPDATE_INVITE_SUCCESS = 'DELETE_INVITE_ERROR'
const UPDATE_INVITE_ERROR = 'DELETE_INVITE_ERROR'

export const OrgActionTypes = {
  SET_CURRENT_ORG_SUCCESS,
  CREATE_ORG_ERROR,
  CREATE_ORG_START,
  CREATE_ORG_SUCCESS,
  UPDATE_ORG_ERROR,
  UPDATE_ORG_START,
  UPDATE_ORG_SUCCESS,
  GET_ORG_START,
  GET_ORG_SUCCESS,
  GET_ORG_ERROR,
  DELETE_INVITE_SUCCESS,
  DELETE_INVITE_ERROR,
  UPDATE_INVITE_SUCCESS,
  UPDATE_INVITE_ERROR
}