const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS'
const CREATE_ORG_ERROR = 'CREATE_ORG_ERROR'
const CREATE_ORG_START = 'CREATE_ORG_START'
const UPDATE_ORG_SUCCESS = 'UPDATE_ORG_SUCCESS'
const UPDATE_ORG_ERROR = 'UPDATE_ORG_ERROR'
const UPDATE_ORG_START = 'UPDATE_ORG_START'
const GET_ORG_START = 'GET_ORG_START'
const GET_ORG_SUCCESS = 'GET_ORG_SUCCESS'
const GET_ORG_ERROR = 'GET_ORG_ERROR'

export const OrgActionTypes = {
  CREATE_ORG_ERROR,
  CREATE_ORG_START,
  CREATE_ORG_SUCCESS,
  UPDATE_ORG_ERROR,
  UPDATE_ORG_START,
  UPDATE_ORG_SUCCESS,
  GET_ORG_START,
  GET_ORG_SUCCESS,
  GET_ORG_ERROR
}